[package]
name = "pathotypr"
version = "0.1.0"
authors = ["Paula Ruiz Rodriguez <paula.ruiz.rodriguez@csic.es>"]
edition = "2021"
description = "Pathotypr is a tool to classify genomes using the train, predict, and classify subcommands."
license = "GPL-3"
repository = "https://github.com/PathoGenOmics-Lab/pathotypr"

[dependencies]
anyhow = "1.0.98"
bio = "2.0.3"
bincode = "1.3"
chrono = "0.4.39"
clap = { version = "4.5.28", features = ["derive"] }
csv = "1.3.1"
env_logger = "0.11.6"
flate2 = "1.0"
indicatif = "0.17.0"
log = "0.4"
nalgebra = "0.33.2"
rand = "0.8.0"
rayon = "1.10.0"
serde = { version = "1.0", features = ["derive"] }
needletail = "0.6.3"
fxhash = "0.2.1"
tempfile = "3.20.0"
ndarray = { version = "0.15", features = ["serde"] }
smartcore   = { version = "0.4.1", features = ["serde"] }
