//! This module handles the `predict` subcommand.
//!
//! It has been refactored to be compatible with the high-performance models
//! generated by the `train` module. Its primary responsibilities are:
//! 1. Loading a model bundle compressed with `zstd`.
//! 2. Verifying model compatibility using the metadata in `ModelConfig`.
//! 3. Efficiently transforming input sequences into sparse feature vectors.
//! 4. Predicting the class for new sequences by aggregating votes from all trees.
//! 5. Calculating confidence metrics and reporting votes for top contenders.

// --- Standard and External Crates ---
use crate::common::{configure_thread_pool, ModelBundle, MODEL_FORMAT_VERSION};
use crate::errors::{
    check_cancelled, AppError, AppResult, CancellationToken, ParallelCancellation,
};
use clap::Parser;
use indicatif::{ProgressBar, ProgressStyle};
use log::{info, warn};
use rayon::prelude::*;
use std::fs::File;
use std::io::{BufWriter, Read, Write};
use std::path::Path;
use std::time::Instant;

// --- Module Constants ---
const VERSION: &str = env!("CARGO_PKG_VERSION");

/// Command-line arguments for the `predict` subcommand.
#[derive(Parser, Debug)]
pub struct PredictArgs {
    /// Path to the input FASTA file containing sequences to classify.
    #[arg(short = 'i', long)]
    pub input: String,
    /// Path to the unified model file created by the `train` command (e.g., `my_model.pathotypr.zst`).
    #[arg(short = 'm', long)]
    pub model: String,
    /// Path for the output file where predictions will be written in TSV format.
    #[arg(short = 'o', long)]
    pub output: String,
    /// Number of CPU threads to use. Defaults to all available cores.
    #[arg(short = 't', long)]
    pub threads: Option<usize>,
    /// Also generate an Excel (.xlsx) file alongside the TSV output.
    #[arg(long, default_value = "false")]
    pub excel: bool,
    /// Cancellation token for stopping the task (GUI only, not CLI).
    #[arg(skip)]
    pub cancel_token: Option<CancellationToken>,
}

/// Reads sequences and their headers from a FASTA file.
///
/// Delegates to `fasta_io::read_fasta_records` — kept as a public alias
/// for backward compatibility with Tauri command code that imports from predict.
pub fn read_fasta_for_prediction(path: &str) -> AppResult<Vec<(String, String)>> {
    crate::fasta_io::read_fasta_records(path)
}

/// Loads the model bundle, decompressing it with `zstd`.
pub fn load_model_bundle(path: &str) -> AppResult<ModelBundle> {
    info!("? Loading model bundle from {}", path);
    let mut file = File::open(path)?;
    let mut compressed_data = Vec::new();
    file.read_to_end(&mut compressed_data)?;

    let decompressed_data = zstd::decode_all(&compressed_data[..])
        .map_err(|e| AppError::Generic(format!("Failed to decompress model file: {}", e)))?;

    let bundle: ModelBundle =
        bincode::deserialize(&decompressed_data[..]).map_err(|e| AppError::Serialization(e))?;

    info!("  Model bundle loaded successfully.");

    // Validate model integrity
    if bundle.trees.is_empty() {
        return Err(AppError::Generic("Model bundle contains no trees.".to_string()));
    }
    if bundle.label_encoder.int_to_label.is_empty() {
        return Err(AppError::Generic("Model bundle has an empty label encoder (no classes).".to_string()));
    }
    crate::common::validate_kmer_size(bundle.config.kmer_size)?;

    Ok(bundle)
}

fn cleanup_generated_outputs(paths: &[String]) {
    for out_path in paths {
        match std::fs::remove_file(out_path) {
            Ok(_) => {}
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => warn!("Failed to remove partial output {}: {}", out_path, e),
        }

        let xlsx_path = Path::new(out_path).with_extension("xlsx");
        match std::fs::remove_file(&xlsx_path) {
            Ok(_) => {}
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
            Err(e) => warn!(
                "Failed to remove partial output {}: {}",
                xlsx_path.display(),
                e
            ),
        }
    }
}

/// Predict a single sparse row against the tree ensemble.
///
/// Returns `(predicted_label, confidence, margin, other_votes_str)`.
fn predict_one_record(
    sparse_row: &[(usize, f32)],
    trees: &[crate::sparse_tree::SparseDecisionTree],
    int_to_label: &[String],
    n_classes: usize,
    total_trees: f32,
) -> (String, f32, f32, String) {
    let mut vote_counts = vec![0u16; n_classes];
    for tree in trees {
        let pred = tree.predict_one(sparse_row);
        if pred < n_classes {
            vote_counts[pred] += 1;
        }
    }

    if let Some((best_class_idx, &winner_vote_count)) =
        vote_counts.iter().enumerate().max_by_key(|(_, count)| *count)
    {
        let mut second_vote_count = 0u16;
        for (class_idx, &vote_count) in vote_counts.iter().enumerate() {
            if class_idx != best_class_idx && vote_count > second_vote_count {
                second_vote_count = vote_count;
            }
        }

        let confidence = if total_trees > 0.0 {
            winner_vote_count as f32 / total_trees
        } else {
            0.0
        };
        let margin = if total_trees > 0.0 {
            winner_vote_count.saturating_sub(second_vote_count) as f32 / total_trees
        } else {
            0.0
        };

        let predicted_label = int_to_label
            .get(best_class_idx)
            .cloned()
            .unwrap_or_else(|| "Unknown".to_string());

        let mut ranked_others: Vec<(usize, u16)> = vote_counts
            .iter()
            .enumerate()
            .filter_map(|(class_idx, &vote_count)| {
                if class_idx != best_class_idx && vote_count > 0 {
                    Some((class_idx, vote_count))
                } else {
                    None
                }
            })
            .collect();
        ranked_others.sort_unstable_by(|a, b| b.1.cmp(&a.1));

        let other_votes_str = ranked_others
            .iter()
            .take(3)
            .map(|(class_idx, vote_count)| {
                let label = int_to_label
                    .get(*class_idx)
                    .map(|s| s.as_str())
                    .unwrap_or("Unknown");
                let percentage = if total_trees > 0.0 {
                    *vote_count as f32 / total_trees
                } else {
                    0.0
                };
                format!("{}:{:.2}", label, percentage)
            })
            .collect::<Vec<String>>()
            .join(",");

        (predicted_label, confidence, margin, other_votes_str)
    } else {
        ("Unknown".to_string(), 0.0, 0.0, String::new())
    }
}

/// Batch size for streaming prediction.
/// Each batch is vectorized + predicted in parallel, then written and freed.
const PREDICT_BATCH_SIZE: usize = 512;

/// Main execution logic for the `predict` subcommand.
///
/// Streams the input FASTA in batches to avoid loading all sequences into
/// memory at once. Each batch is vectorized and predicted in parallel with
/// rayon, then results are written immediately and the batch is freed.
pub fn run(args: PredictArgs) -> AppResult<()> {
    configure_thread_pool(args.threads);

    let cancel_token = &args.cancel_token;
    check_cancelled(cancel_token)?;

    let overall_start = Instant::now();

    // --- Model Loading and Validation ---
    let bundle = load_model_bundle(&args.model)?;

    check_cancelled(cancel_token)?;

    info!(
        "  Model trained with pathotypr v{}, k={}, format v{}.",
        bundle.config.pathotypr_version, bundle.config.kmer_size, bundle.config.format_version
    );
    if bundle.config.format_version != MODEL_FORMAT_VERSION {
        return Err(AppError::Generic(format!(
            "Incompatible model format (v{}, expected v{}). Please retrain the model with this version of pathotypr.",
            bundle.config.format_version, MODEL_FORMAT_VERSION
        )));
    }
    if bundle.config.pathotypr_version != VERSION {
        warn!("Model was trained with a different version of pathotypr (v{}). Current version is v{}. Results may vary.", bundle.config.pathotypr_version, VERSION);
    }

    let total_trees = bundle.trees.len() as f32;
    let n_classes = bundle.label_encoder.int_to_label.len();
    let kmer_size = bundle.config.kmer_size;

    // --- Open output files before streaming ---
    let generated_outputs = vec![args.output.clone()];
    let mut output_file = match File::create(&args.output) {
        Ok(f) => BufWriter::new(f),
        Err(e) => return Err(AppError::Io(e)),
    };
    if let Err(e) = writeln!(
        output_file,
        "Header\tPredicted_Lineage\tConfidence\tConfidence_Margin\tOther_Votes"
    ) {
        drop(output_file);
        cleanup_generated_outputs(&generated_outputs);
        return Err(AppError::Io(e));
    }

    let excel_headers = [
        "Header",
        "Predicted_Lineage",
        "Confidence",
        "Confidence_Margin",
        "Other_Votes",
    ];
    let mut excel_writer = if args.excel {
        match crate::common::ExcelStreamWriter::new(&args.output, &excel_headers) {
            Ok(mut writer) => {
                writer.set_conditional_formatting(2, 0.5, 0.9);
                writer.set_conditional_formatting(3, 0.1, 0.5);
                Some(writer)
            }
            Err(e) => {
                warn!("⚠️ Could not initialize Excel writer: {}", e);
                None
            }
        }
    } else {
        None
    };

    // --- Stream FASTA in batches ---
    // Uses needletail for parsing (handles .gz transparently, ~3× faster).
    info!("▶ Streaming input FASTA in batches of {}...", PREDICT_BATCH_SIZE);
    let mut fasta_reader = needletail::parse_fastx_file(&args.input).map_err(|e| {
        AppError::Parsing(format!("Failed to open FASTA {}: {}", args.input, e))
    })?;

    let pb = ProgressBar::new_spinner();
    pb.set_style(ProgressStyle::with_template(
        "  {spinner:.cyan} Predicted: {pos} sequences ({elapsed})",
    )?);
    pb.enable_steady_tick(std::time::Duration::from_millis(120));

    let cancellation = ParallelCancellation::new(cancel_token);
    let mut total_predicted = 0u64;
    let mut found_any = false;
    let mut batch: Vec<(String, String)> = Vec::with_capacity(PREDICT_BATCH_SIZE);

    loop {
        // Fill batch from FASTA stream
        batch.clear();
        loop {
            match fasta_reader.next() {
                Some(Ok(record)) => {
                    let header = std::str::from_utf8(record.id())
                        .map_err(|e| AppError::Parsing(format!("Non-UTF8 header: {}", e)))?
                        .to_string();
                    let seq = String::from_utf8(record.seq().to_vec())
                        .map_err(|e| AppError::Parsing(format!("Non-UTF8 sequence in {}: {}", header, e)))?;
                    if seq.is_empty() {
                        warn!("Skipping entry with empty sequence: {}", header);
                        continue;
                    }
                    batch.push((header, seq));
                    if batch.len() >= PREDICT_BATCH_SIZE {
                        break;
                    }
                }
                Some(Err(e)) => {
                    drop(output_file);
                    cleanup_generated_outputs(&generated_outputs);
                    return Err(AppError::Parsing(format!("Error reading FASTA record: {}", e)));
                }
                None => break, // EOF
            }
        }

        if batch.is_empty() {
            break;
        }
        found_any = true;

        // Vectorize batch in parallel
        let sequences: Vec<&str> = batch.iter().map(|(_, seq)| seq.as_str()).collect();
        let x_sparse = bundle.vectorizer.transform_sparse(&sequences, kmer_size);

        // Predict batch in parallel
        let trees = &bundle.trees;
        let int_to_label = &bundle.label_encoder.int_to_label;

        let batch_predictions: Vec<(String, f32, f32, String)> = x_sparse
            .par_iter()
            .map(|sparse_row| {
                if cancellation.is_cancelled() {
                    return (String::new(), 0.0, 0.0, String::new());
                }
                predict_one_record(sparse_row, trees, int_to_label, n_classes, total_trees)
            })
            .collect();

        cancellation.check_after().map_err(|e| {
            cleanup_generated_outputs(&generated_outputs);
            e
        })?;

        // Write batch results immediately
        for (i, (header, _)) in batch.iter().enumerate() {
            let (ref pred, conf, margin, ref others) = batch_predictions[i];
            if let Err(e) = writeln!(
                output_file,
                "{}\t{}\t{:.4}\t{:.4}\t{}",
                header, pred, conf, margin, others
            ) {
                drop(output_file);
                cleanup_generated_outputs(&generated_outputs);
                return Err(AppError::Io(e));
            }

            let row = vec![
                header.clone(),
                pred.clone(),
                format!("{:.4}", conf),
                format!("{:.4}", margin),
                others.clone(),
            ];
            let mut disable_excel = false;
            if let Some(writer) = excel_writer.as_mut() {
                if let Err(e) = writer.write_row(&row) {
                    warn!("⚠️ Could not append Excel row: {}", e);
                    disable_excel = true;
                }
            }
            if disable_excel {
                excel_writer = None;
            }
        }

        total_predicted += batch.len() as u64;
        pb.set_position(total_predicted);
        // batch + x_sparse + batch_predictions are dropped here, freeing memory
    }

    pb.finish_with_message(format!("Prediction complete ({} sequences).", total_predicted));

    if !found_any {
        drop(output_file);
        cleanup_generated_outputs(&generated_outputs);
        return Err(AppError::NotEnoughData(
            "No records found in the input FASTA file.".to_string(),
        ));
    }

    if let Err(e) = output_file.flush() {
        drop(output_file);
        cleanup_generated_outputs(&generated_outputs);
        return Err(AppError::Io(e));
    }
    drop(output_file);

    // Write Excel file if requested
    if args.excel {
        check_cancelled(cancel_token).map_err(|e| {
            cleanup_generated_outputs(&generated_outputs);
            e
        })?;
        if let Some(writer) = excel_writer.take() {
            match writer.finish() {
                Ok(xlsx_path) => info!("📊 Excel file written to {}", xlsx_path),
                Err(e) => warn!("⚠️ Could not write Excel file: {}", e),
            }
        }
    }

    info!(
        "🏁 Process completed in {:.2} seconds.",
        overall_start.elapsed().as_secs_f32()
    );
    Ok(())
}
