//! This module handles the `predict` subcommand.
//!
//! It has been refactored to be compatible with the high-performance models
//! generated by the `train` module. Its primary responsibilities are:
//! 1. Loading a model bundle compressed with `zstd`.
//! 2. Verifying model compatibility using the metadata in `ModelConfig`.
//! 3. Efficiently transforming input sequences into sparse feature vectors.
//! 4. Predicting the class for new sequences by aggregating votes from all trees.
//! 5. Calculating confidence metrics and reporting votes for top contenders.

// --- Standard and External Crates ---
use crate::common::ModelBundle;
use crate::errors::{AppError, AppResult};
use clap::Parser;
use indicatif::{ProgressBar, ProgressStyle};
use log::{debug, info, warn};
use rustc_hash::FxHashMap;
// MODIFIED: Using f32-based DenseMatrix.
use smartcore::linalg::basic::matrix::DenseMatrix;
use std::fs::File;
use std::io::{BufRead, BufReader, Read, Write};
use std::time::Instant;

// --- Module Constants ---
const VERSION: &str = env!("CARGO_PKG_VERSION");

/// Command-line arguments for the `predict` subcommand.
#[derive(Parser, Debug)]
pub struct PredictArgs {
    /// Path to the input FASTA file containing sequences to classify.
    #[arg(short = 'i', long)]
    pub input: String,
    /// Path to the unified model file created by the `train` command (e.g., `my_model.pathotypr.zst`).
    #[arg(short = 'm', long)]
    pub model: String,
    /// Path for the output file where predictions will be written in TSV format.
    #[arg(short = 'o', long)]
    pub output: String,
    /// Number of CPU threads to use. Defaults to all available cores.
    #[arg(short = 't', long)]
    pub threads: Option<usize>,
}

/// Reads sequences and their headers from a FASTA file.
fn read_fasta_for_prediction(path: &str) -> AppResult<Vec<(String, String)>> {
    let file = File::open(path)?;
    let pb = ProgressBar::new(file.metadata()?.len());
    let style = ProgressStyle::default_bar()
        .template("{spinner:.green} [{elapsed_precise}] [{bar:40.cyan/blue}] {bytes}/{total_bytes} ({eta})")?
        .progress_chars("#>-");
    pb.set_style(style);

    let reader = BufReader::new(pb.wrap_read(file));
    let mut records = Vec::new();
    let mut current_header = String::new();
    let mut current_seq = String::new();

    for line in reader.lines() {
        let line = line?;
        if line.starts_with('>') {
            if !current_header.is_empty() {
                records.push((current_header.clone(), current_seq.clone()));
            }
            current_header = line.trim_start_matches('>').to_string();
            current_seq.clear();
        } else {
            current_seq.push_str(line.trim());
        }
    }
    if !current_header.is_empty() {
        records.push((current_header, current_seq));
    }
    pb.finish_with_message("FASTA reading complete");
    Ok(records)
}

/// Loads the model bundle, decompressing it with `zstd`.
fn load_model_bundle(path: &str) -> AppResult<ModelBundle> {
    info!("? Loading model bundle from {}", path);
    let mut file = File::open(path)?;
    let mut compressed_data = Vec::new();
    file.read_to_end(&mut compressed_data)?;

    let decompressed_data = zstd::decode_all(&compressed_data[..])
        .map_err(|e| AppError::Generic(format!("Failed to decompress model file: {}", e)))?;

    let bundle: ModelBundle = bincode::deserialize(&decompressed_data[..])
        .map_err(|e| AppError::Serialization(e))?;

    info!("  Model bundle loaded successfully.");
    Ok(bundle)
}

/// Main execution logic for the `predict` subcommand.
pub fn run(args: PredictArgs) -> AppResult<()> {
    if let Some(n) = args.threads {
        debug!("Setting number of threads to: {}", n);
        rayon::ThreadPoolBuilder::new().num_threads(n).build_global()
            .map_err(|e| AppError::Generic(format!("Failed to build thread pool: {}", e)))?;
    }

    let overall_start = Instant::now();

    // --- Model Loading and Validation ---
    let bundle = load_model_bundle(&args.model)?;
    
    info!("  Model trained with pathotypr v{}, k={}.", bundle.config.pathotypr_version, bundle.config.kmer_size);
    if bundle.config.pathotypr_version != VERSION {
        warn!("Model was trained with a different version of pathotypr (v{}). Current version is v{}. Results may vary.", bundle.config.pathotypr_version, VERSION);
    }

    // --- Data Loading ---
    info!("? Reading input FASTA file: {}", args.input);
    let records = read_fasta_for_prediction(&args.input)?;
    if records.is_empty() {
        return Err(AppError::NotEnoughData("No records found in the input FASTA file.".to_string()));
    }

    // --- Feature Transformation ---
    info!("? Generating k-mers and transforming features into sparse vectors...");
    let sequences: Vec<String> = records.iter().map(|(_, seq)| seq.clone()).collect();
    // MODIFIED: Call transform_sparse and handle the sparse f32 data format.
    let x_data_sparse = bundle.vectorizer.transform_sparse(&sequences, bundle.config.kmer_size);
    debug!("  Transformed {} sequences into sparse feature vectors.", records.len());

    // --- Prediction ---
    info!("? Predicting lineages by aggregating tree votes...");
    let mut predictions_with_metrics = Vec::new();
    let total_trees = bundle.trees.len() as f32;
    let n_features = bundle.vectorizer.num_features;
    let default_prediction = "Unknown".to_string();

    let pb = ProgressBar::new(x_data_sparse.len() as u64);
    let style = ProgressStyle::default_bar().template("  {spinner:.cyan} Predicting: [{bar:40.green/yellow}] {pos}/{len} ({eta})")?.progress_chars("=> ");
    pb.set_style(style);

    for sparse_row in x_data_sparse {
        // MODIFIED: Convert the sparse row to a dense f32 row for prediction.
        let mut dense_row = vec![0.0_f32; n_features];
        for &(feature_idx, val) in &sparse_row {
            if feature_idx < n_features {
                dense_row[feature_idx] = val;
            }
        }
        let x_row = DenseMatrix::from_2d_vec(&vec![dense_row])?;
        
        let mut votes: FxHashMap<usize, u16> = FxHashMap::default();

        for tree in &bundle.trees {
            let prediction = tree.predict(&x_row)?[0];
            *votes.entry(prediction).or_insert(0) += 1;
        }

        let mut sorted_votes: Vec<(&usize, &u16)> = votes.iter().collect();
        sorted_votes.sort_by(|a, b| b.1.cmp(a.1));

        if let Some(winner) = sorted_votes.get(0) {
            let best_class_idx = *winner.0;
            let winner_vote_count = *winner.1;
            
            let second_vote_count = sorted_votes.get(1).map_or(0, |&(_, count)| *count);

            let confidence = winner_vote_count as f32 / total_trees;
            let margin = (winner_vote_count - second_vote_count) as f32 / total_trees;

            let predicted_label = bundle.label_encoder.int_to_label
                .get(best_class_idx)
                .cloned()
                .unwrap_or_else(|| default_prediction.clone());
            
            let other_votes_str = sorted_votes
                .iter()
                .skip(1)
                .take(3)
                .map(|(class_idx, vote_count)| {
                    let label = bundle.label_encoder.int_to_label.get(**class_idx).unwrap_or(&default_prediction);
                    let percentage = **vote_count as f32 / total_trees;
                    format!("{}:{:.2}", label, percentage)
                })
                .collect::<Vec<String>>()
                .join(",");
            
            predictions_with_metrics.push((predicted_label, confidence, margin, other_votes_str));
        } else {
            predictions_with_metrics.push((default_prediction.clone(), 0.0, 0.0, String::new()));
        }
        pb.inc(1);
    }
    pb.finish_with_message("Prediction complete.");

    // --- Write Output ---
    info!("? Writing predictions to {}", args.output);
    let mut output_file = File::create(&args.output)?;
    writeln!(output_file, "Header\tPredicted_Lineage\tConfidence\tConfidence_Margin\tOther_Votes")?;
    
    for (i, (header, _)) in records.iter().enumerate() {
        if let Some((pred, conf, margin, others)) = predictions_with_metrics.get(i) {
            writeln!(output_file, "{}\t{}\t{:.4}\t{:.4}\t{}", header, pred, conf, margin, others)?;
        } else {
            writeln!(output_file, "{}\t{}\t{:.4}\t{:.4}\t", header, default_prediction, 0.0, 0.0)?;
        }
    }
    
    info!("🏁 Process completed in {:.2} seconds.", overall_start.elapsed().as_secs_f32());
    Ok(())
}